//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlWorks.UI.BarTender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Data\\ControlWorks\\BarTender\\Documents")]
        public string BartenderFilesLocation {
            get {
                return ((string)(this["BartenderFilesLocation"]));
            }
            set {
                this["BartenderFilesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Data\\cw\\templates")]
        public string TemplateFilesLocation {
            get {
                return ((string)(this["TemplateFilesLocation"]));
            }
            set {
                this["TemplateFilesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string DefaultBoxHeight {
            get {
                return ((string)(this["DefaultBoxHeight"]));
            }
            set {
                this["DefaultBoxHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string DefaultBoxWidth {
            get {
                return ((string)(this["DefaultBoxWidth"]));
            }
            set {
                this["DefaultBoxWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Landscape")]
        public string DefaultOrientation {
            get {
                return ((string)(this["DefaultOrientation"]));
            }
            set {
                this["DefaultOrientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public string DefaultInfeedSpeed {
            get {
                return ((string)(this["DefaultInfeedSpeed"]));
            }
            set {
                this["DefaultInfeedSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public string DefaultPrinterSpeed {
            get {
                return ((string)(this["DefaultPrinterSpeed"]));
            }
            set {
                this["DefaultPrinterSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Front and Side")]
        public string DefaultLabelPlacement {
            get {
                return ((string)(this["DefaultLabelPlacement"]));
            }
            set {
                this["DefaultLabelPlacement"] = value;
            }
        }
    }
}
